name: CI/CD Workflow for Flask Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-checkout-and-setup:
    uses: ./.github/workflows/checkout-and-setup.yml

  run-tests:
    needs: run-checkout-and-setup
    uses: ./.github/workflows/run-tests.yml

  docker-build-and-push:
    needs: run-tests
    uses: ./.github/workflows/docker-build-and-push.yml

  minikube-helm-deploy:
    needs: docker-build-and-push
    uses: ./.github/workflows/minikube-helm-deploy.yml
