name: Run Tests

on: workflow_call

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Run Unit Tests
      run: |
        python -m unittest discover -s . -p "test_*.py"
